swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10011
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /gets:
    # binds a127 app logic to a route
    x-swagger-router-controller: Controller
    get:
      description: Returns 'Hello' to the caller
      operationId: Gets
      parameters:
        - name: name
          in: query
          description: Saying Hi to myself
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /posts:
    x-swagger-router-controller: Controller
    post:
      operationId: Posts
      description: Add another name
      # Name to be added. 
      parameters:
        - name: user
          description: A new name
          in: body
          required: false
          schema:
            $ref: "#/definitions/PostName"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /puts:
    x-swagger-router-controller: Controller
    put:
      operationId: Puts
      description: Update your name
    #  Update Name 
      parameters:
        - name: id
          in: query
          description: name id 
          required: false
          type: string
        - name: title
          description: Name Properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Name"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /deletes:
    x-swagger-router-controller: Controller
    delete:
      operationId: Deletes
      description: delete a name
      # define the parameters
      parameters:
        - name: id
          description: name id
          type: string
          in: query
          required: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
#Response Definition for /Gets
  GetsResponse:
    properties:
      message:
        type: string
        description: message to user
      description:
        type: string
        description: a short comment
#Response Definition for /Post
  PostName:
    type: object
    properties:
      first:
        type: string
      last:
        type: string
#Response Definition for General Success        
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description
#Response Definition for Error's       
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
#Name object        
  Name:
    type: object
    properties:
      first_Name:
        type: string
        description: task First name
      last_Name:
        type: string
        description: task Last name
    required:
      - first_Name
      - last_Name
